server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: macro
      password: 123456
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
