server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.102.109.216/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Vae970109vae

mybatis:
  mapper-locations:
    -classpath:mapper/*.xml
    -classpath:com/**/mapper/*.xml

