#version: '3'
#
#services:
#  gerrit:
#    image: gerritcodereview/gerrit:latest
#    container_name: gerrit
#    ports:
#      - "8080:8080"
#      - "29418:29418"
#    volumes:
#      - ./gerrit_data:/var/gerrit/git
#      - ./gerrit_cache:/var/gerrit/cache
#      - ./gerrit_index:/var/gerrit/index
##      - ./gerrit_hooks:/var/gerrit/hooks
#  http密钥
#  v9oIiv1UD1/RNWMoVqvAram5PTWCtB3ipmVHQh2fGg

version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit
    container_name: gerrit
    ports:
      - "80:80"
      - "8080:8080"
      - "29418:29418"
    volumes:
      - gerrit_data:/var/gerrit/review_site
      - ./tools/hooks:/var/gerrit/hooks
    environment:
      - AUTH_TYPE=DEVELOPMENT_BECOME_ANY_ACCOUNT
      - CANONICAL_WEB_URL=http://localhost:8080
      - DATABASE_TYPE=H2
      - JAVA_HEAPLIMIT=2g
      - WEBSESSION_MAXAGE=31536000
    restart: always

volumes:
  gerrit_data:
