server:
  port: 8103
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://macro:123456@localhost:8004/eureka/
    register-with-eureka: true
    fetch-registry: true
